# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lv2lnLesi017AWvOATfCtcUS1hcnM672
"""

test_list = [(3,4,6,723),(1,2), (34,234, 34,)]
output = [(1,2),(3,4,6,723),(134, 234, 34,)]
test_list.sort()
output.sort()

print("Lista Ordenada", test_list) 
print("Lista Ordenada", output)


# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SannHYmk_8lzVW3_XGBohoyUVRv0vdMQ
"""

frase = input('cual es la frase?: ')
letrax = input('cual es la letra?: ')
contador = 0

for letra in frase: 
  if letra == letrax:
     contador += 1

print("La letra " + letrax + " se repite " + str(contador)+ " veces")