# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eWgjuhPubPX_WpQBxy-p5kyHOhg8b06C
"""

def invertir_lista(li):
  lista_invert = []
  cuenta = len(li)-1
  while cuenta >=0:
    lista_invert.append(li[cuenta]) 
    cuenta-=1
  return lista_invert

lista = []
num_lista = 10
for i in range (num_lista):
  numeros = input('numero?: ')
  lista.append(numeros)
print(invertir_lista(lista))