# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fyFGQN-ikc4xuP8tHDtueUrqmyyRB615
"""

Primera = []
Segunda = []
ra = input("num1 de primera ficha: ")
da = input("num2 de primera ficha: ")
fch = input("num1 de segunda ficha: ")
fchx = input("num2 de segunda ficha: ")

if ra == fch or fchx:
  print('Las fichas pueden encajar')
else:
   print('Las fichas no pueden encajar')

if da == fch or fchx:
  print('las fichas pueden encajar')
else:
   print('las fichas no pueden encajar')
Segunda.append(fch)
Segunda.append(fchx)

Primera.append(ra)
Primera.append(da)
print(Primera)
print(Segunda)