# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u8q9tCrzHm9DxlQN4ANMcR7aXdn7IApW
"""

import random
def suma_dado(n:int):
  diccionario = {}
  for i in range(n):
    dado = random.randint(1,6)
    dadox = random.randint(1,6)
    suma = dado + dadox
    if suma not in diccionario:
      diccionario[suma] = 0
    if suma in diccionario:
      diccionario[suma] += 1
  return diccionario 

print(suma_dado(5))