# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EJX1TFyrGqJEuQrMOPZjZfB_JnBIDEae
"""

t1 = ( clave, [don1,don2], clave2 ,[valores])

d = dict(zip(t1[0::2],t1[1::2]) )
don1 = input('nombre?: ')
don2 = input('nombre?: ')
clave = input('hola/holi: ')
clave2 = input('saludos: ')
valores = input('dia/tarde/noche: ')


print(d)